config/routes.rb
Rails.application.routes.draw do
  resources :selections
  resources :rankings do 
      collection do  
        get :show_create_rankings
        post :create_rankings
      end
    end
  resources :ratings 
  resources :cards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  belongs_to :card
  belongs_to :rating
  belongs_to :selection
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  before_action :set_ranking, only: %i[ show edit update destroy ]

  # GET /rankings or /rankings.json
  def index
    @rankings = Ranking.all
  end

  # GET /rankings/1 or /rankings/1.json
  def show
  end

  # GET /rankings/new
  def new
    @ranking = Ranking.new
  end

  # GET /rankings/1/edit
  def edit
  end

  # POST /rankings or /rankings.json
  def create
    @ranking = Ranking.new(ranking_params)

    respond_to do |format|
      if @ranking.save
        format.html { redirect_to @ranking, notice: "Ranking was successfully created." }
        format.json { render :show, status: :created, location: @ranking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rankings/1 or /rankings/1.json
  def update
    respond_to do |format|
      if @ranking.update(ranking_params)
        format.html { redirect_to @ranking, notice: "Ranking was successfully updated." }
        format.json { render :show, status: :ok, location: @ranking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rankings/1 or /rankings/1.json
  def destroy
    @ranking.destroy
    respond_to do |format|
      format.html { redirect_to rankings_url, notice: "Ranking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show_create_rankings 
    @cards = Card.all
    @ratings = Rating.all
  end

  def create_rankings 
    card_names = params.keys - %w(authenticity_token commit controller action)
    params.permit(card_names).each do|card_name, rating_id| 
      Ranking.create(
        card: Card.find_by_name(card_name),
        rating_id: rating_id,
        selection: Selection.last
      )
    end
    @rankings = Selection.last.rankings
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ranking
      @ranking = Ranking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ranking_params
      params.require(:ranking).permit(:card_id, :rating_id, :selection_id)
    end
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_form.html.erb
<%= form_with(model: ranking) do |form| %>
  <% if ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ranking.errors.count, "error") %> prohibited this ranking from being saved:</h2>

      <ul>
        <% ranking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :card_id %>
    <%= collection_select( :ranking, :card_id, Card.all, :id, :name,  { multiple: false}) %>
  </div>

  <div class="field">
    <%= form.label :rating_id %>
    <%= collection_select( :ranking, :rating_id, Rating.all, :id, :name, { multiple: false}) %>
  </div>

  <div class="field">
    <%= form.label :selection_id %>
    <%= collection_select( :ranking, :selection_id, Selection.all, :id, :name, { multiple: false}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rankings/create_rankings.erb
<% @rankings.each do |ranking| %>
    <%= ranking.card.name %>
    <%= ranking.selection.name %>
    <%= ranking.rating.name %>
<%end %>

app/views/rankings/edit.html.erb
<h1>Editing Ranking</h1>

<%= render 'form', ranking: @ranking %>

<%= link_to 'Show', @ranking %> |
<%= link_to 'Back', rankings_path %>

app/views/rankings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rankings</h1>

<table>
  <thead>
    <tr>
      <th>Card</th>
      <th>Rating</th>
      <th>Selection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rankings.each do |ranking| %>
      <tr>
      <%# TODO -> rankings with the same selection can't have the same card %>
        <td><%= ranking.card.name %></td>
        <td><%= ranking.rating.name %></td>
        <td><%= ranking.selection.name %></td>
        <td><%= link_to 'Show', ranking %></td>
        <td><%= link_to 'Edit', edit_ranking_path(ranking) %></td>
        <td><%= link_to 'Destroy', ranking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ranking', new_ranking_path %>

app/views/rankings/new.html.erb
<h1>New Ranking</h1>

<%= render 'form', ranking: @ranking %>

<%= link_to 'Back', rankings_path %>

app/views/rankings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card:</strong>
  <%= @ranking.card_id %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @ranking.rating_id %>
</p>

<p>
  <strong>Selection:</strong>
  <%= @ranking.selection_id %>
</p>

<%= link_to 'Edit', edit_ranking_path(@ranking) %> |
<%= link_to 'Back', rankings_path %>

app/views/rankings/show_create_rankings.erb
<%= form_with(url: url_for(controller: :rankings, action: :create_rankings)) do |f| %>
    <dl>
<% @cards.each do |card|%>
<dt>Card Name <%= card.name %></dt>
    <dd>  
        <% @ratings.each do |rating| %>
            <input type='radio' name='<%=card.name %>' value='<%= rating.id%>'>
            <%= rating.name %>
        <% end %>
    </dd>
<% end%>
</dl>
<%= f.submit %>
<% end %>