config/routes.rb
Rails.application.routes.draw do
  resources :selections
  resources :rankings do 
      collection do  
        get :show_create_rankings
        post :create_rankings
      end
    end
  resources :ratings 
  resources :cards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/selection.rb
class Selection < ApplicationRecord
    
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_selection, only: %i[ show edit update destroy ]

  # GET /selections or /selections.json
  def index
    @selections = Selection.all
  end

  # GET /selections/1 or /selections/1.json
  def show
  end

  # GET /selections/new
  def new
    @selection = Selection.new
  end

  # GET /selections/1/edit
  def edit
  end

  # POST /selections or /selections.json
  def create
    @selection = Selection.new(selection_params)

    respond_to do |format|
      if @selection.save
        format.html { redirect_to @selection, notice: "Selection was successfully created." }
        format.json { render :show, status: :created, location: @selection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selections/1 or /selections/1.json
  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: "Selection was successfully updated." }
        format.json { render :show, status: :ok, location: @selection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1 or /selections/1.json
  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url, notice: "Selection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def selection_params
      params.require(:selection).permit(:name)
    end
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/selections/_form.html.erb
<%= form_with(model: selection) do |form| %>
  <% if selection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(selection.errors.count, "error") %> prohibited this selection from being saved:</h2>

      <ul>
        <% selection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/selections/edit.html.erb
<h1>Editing Selection</h1>

<%= render 'form', selection: @selection %>

<%= link_to 'Show', @selection %> |
<%= link_to 'Back', selections_path %>

app/views/selections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Selections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selections.each do |selection| %>
      <tr>
        <td><%= selection.name %></td>
        <td><%= link_to 'Show', selection %></td>
        <td><%= link_to 'Edit', edit_selection_path(selection) %></td>
        <td><%= link_to 'Destroy', selection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selection', new_selection_path %>

app/views/selections/new.html.erb
<h1>New Selection</h1>

<%= render 'form', selection: @selection %>

<%= link_to 'Back', selections_path %>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @selection.name %>
</p>

<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>